apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: tcp-9000
      port: 9000
      targetPort: 9000
      protocol: TCP