apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: NodePort
  selector:
    app: postgresql
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
