kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-vol
  labels:
    app: prometheus
spec:
  storageClassName: nfs-basic-storages
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi