kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-vol
  labels:
    app: grafana
spec:
  storageClassName: nfs-basic-storages
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi