apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
data:
  rabbitmq.conf: |-
    loopback_users.guest = false
    total_memory_available_override_value = 1073741824
    collect_statistics_interval = 10000
    collect_statistics_interval = 5000
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    management.path_prefix = /rabbitmq
    prometheus.return_per_object_metrics = false
    prometheus.path = /metrics
    prometheus.tcp.port =  15692
