apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      volumes:
        - name: rabbitmq-vol
          persistentVolumeClaim:
            claimName: infra
        - name: rabbitmq
          configMap:
            defaultMode: 0755
            name: rabbitmq
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.9-management
          imagePullPolicy: Always
          volumeMounts:
            - name: rabbitmq-vol
              subPath: rabbitmq-vol
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
          ports:
            - name: queue-port
              containerPort: 5672
              protocol: TCP
            - name: queue-port-tls
              containerPort: 5671
              protocol: TCP
            - name: management-port
              containerPort: 15672
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 5672
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 5672
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "waTa8chahX"
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "512Mi"