apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - name: tcp-80
      port: 80
      targetPort: 80
      protocol: TCP
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5.1.3-apache
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 80
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: PMA_HOST
              value: "mariadb"
            - name: PMA_USER
              value: "root"
            - name: PMA_PASSWORD
              value: "aiwu7af1uX"
            - name: PMA_ABSOLUTE_URI
              value: "http://platform.nuomitech.cn/phpmyadmin/"
