apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      volumes:
        - name: nacos
          configMap:
            defaultMode: 0755
            name: nacos
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.2.0
          imagePullPolicy: Always
          volumeMounts:
            - name: nacos
              mountPath: /home/nacos/conf/application.properties
              subPath: application.properties
          ports:
            - name: tcp
              containerPort: 8848
              protocol: TCP
          # livenessProbe:
          #   initialDelaySeconds: 90
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   tcpSocket:
          #     port: 8848
          # readinessProbe:
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   tcpSocket:
          #     port: 8848
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: MODE
              value: "standalone"
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "512Mi"