apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - name: tcp-8848
      port: 8848
      targetPort: 8848
      protocol: TCP
    - name: tcp-9848
      port: 9848
      targetPort: 9848
      protocol: TCP
    - name: tcp-9849
      port: 9849
      targetPort: 9849
      protocol: TCP