apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: epub-dev
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - name: tcp-3306
      port: 3306
      targetPort: 3306
      protocol: TCP
