apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-vol
        - name: mysql
          configMap:
            defaultMode: 0755
            name: mysql
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: Always
          volumeMounts:
            - name: mysql-vol
              subPath: mysql-vol
              mountPath: /var/lib/mysql
            - name: mysql
              mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              subPath: mysqld.cnf
          ports:
            - name: tcp
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 3306
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 3306
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "asset"
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "512Mi"