---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlassian
  labels:
    app: atlassian
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/atlassian
    server: 172.16.115.11

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: atlassian
  labels:
    app: atlassian
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "50Gi"
  selector:
    matchLabels:
      app: atlassian
